image: eclipse-temurin:21-jdk

stages:
  - build
  - upload

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

  RCLONE_REMOTE: "MebahelModding"
  RCLONE_DEST_PATH: "ModsBuilds"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/wrapper
    - .gradle/caches

# ---------------------------
# 1) BUILD DU MOD
# ---------------------------
build_mod:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week
  only:
    - "1.20"

# ---------------------------
# 2) UPLOAD VERS GOOGLE DRIVE
# ---------------------------
upload_to_drive:
  stage: upload
  needs:
    - build_mod
  image: alpine:latest

  before_script:
    - mkdir -p /root/.config/rclone
    - echo "$RCLONE_CONF_BASE64" | base64 -d > /root/.config/rclone/rclone.conf
    - apk add --no-cache curl unzip grep coreutils
    - curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
    - unzip rclone-current-linux-amd64.zip
    - cp rclone-*-linux-amd64/rclone /usr/bin/

  script:
    - echo "Liste des fichiers dans build/libs"
    - ls -R build/libs || true

    # On prend le premier .jar qui n'est pas un -sources.jar
    - JAR=$(ls build/libs/*.jar | grep -v 'sources' | head -n 1 || true)

    - if [ -z "$JAR" ]; then echo "Aucun jar valide trouve dans build/libs"; exit 1; fi

    - echo "Jar selectionne $JAR"
    - rclone copy "$JAR" "$RCLONE_REMOTE:$RCLONE_DEST_PATH/" -v

  only:
    - "1.20"
